"""Removed comment system

Revision ID: 49afe8577fee
Revises: 592f648c3ebf
Create Date: 2024-12-05 11:31:47.486251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49afe8577fee'
down_revision = '592f648c3ebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_table')
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_column('comment_count')
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('comment_count', sa.INTEGER(), nullable=True))

    op.create_table('comment_table',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.VARCHAR(length=100), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post_table.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
