"""Changed likes to likike_count in Post

Revision ID: 592f648c3ebf
Revises: affca71cd6f5
Create Date: 2024-12-05 03:38:37.543879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '592f648c3ebf'
down_revision = 'affca71cd6f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('like_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post_table', schema=None) as batch_op:
        batch_op.drop_column('like_count')

    # ### end Alembic commands ###
