"""Changed comment to content in PostComments

Revision ID: f8e108d04f01
Revises: 84dd54868976
Create Date: 2024-12-04 00:27:13.866846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8e108d04f01'
down_revision = '84dd54868976'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.String(length=100), nullable=True))
        batch_op.drop_column('comment')

    with op.batch_alter_table('notification_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=200), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=200), nullable=True))
        batch_op.drop_column('message')

    with op.batch_alter_table('comment_table', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('content')

    # ### end Alembic commands ###
